#!/bin/sh
### BEGIN INIT INFO
# Provides:          getmail
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop getmail script handler
### END INIT INFO

set -e

NAME=getmail-daemon
PIDFILE=/var/run/getmail-daemon.pid
USER=root
GROUP=root
DAEMON=/usr/sbin/getmail-daemon

. /lib/lsb/init-functions

start_daemon () {
  start-stop-daemon --background --start \
    --pidfile $PIDFILE \
    --make-pidfile --chuid $USER --user $USER --group $GROUP \
    --exec $DAEMON
}

stop_daemon () {
  start-stop-daemon --stop --pidfile $PIDFILE
}

case $1 in
  start)
    log_daemon_msg "Starting getmail script" "getmail"
    start_daemon
    log_end_msg $?
  ;;
  stop)
    log_daemon_msg "Stopping getmail script" "getmail"
    stop_daemon
    log_end_msg $?
  ;;
  restart | reload | force-reload | graceful)
    log_daemon_msg "Reloading getmail script" "getmail"
    stop_daemon
    start_daemon
    log_end_msg 0
  ;;
  status)
    status_of_proc -p "$PIDFILE" "$DAEMON" getmail && exit 0 || exit $?
  ;;
  *)
    log_action_msg "Usage: $0 {start|stop|restart|reload|force-reload|graceful|status}" || true
    exit 1
  ;;
esac
